# fly.toml app configuration file generated for gpt-cursor-runner-devv on 2025-07-07T01:56:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt-cursor-runner-devv'
primary_region = 'sea'

[build]

[env]
  NODE_ENV = 'production'
  PUBLIC_RUNNER_URL = 'https://runner.thoughtmarks.app'

[http_service]
  internal_port = 5051
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'get'
    path = '/health'

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'get'
    path = '/slack/test'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
