// GHOST RUNNER System Paths;
export const _GHOST_STATUS_PATH =;
  '/Users/sawyer/gitSync/.cursor-cache/CYOPS/ghost/status.json';
;
// CYOPS (DEV Agent) Paths;
export const _CYOPS_PATCH_PATH =';'';
  '/Users/sawyer/gitSync/.cursor-cache/CYOPS/patches/';
export const _CYOPS_SUMMARY_PATH =';'';
  '/Users/sawyer/gitSync/.cursor-cache/CYOPS/summaries/'';'';
export const _CYOPS_LOG_PATH = '/Users/sawyer/gitSync/gpt-cursor-runner/logs/';
export const _CYOPS_HEARTBEAT_PATH =';'';
  '/Users/sawyer/gitSync/.cursor-cache/CYOPS/.heartbeat/';
;
// MAIN (BRAUN Agent) Paths;
export const _MAIN_PATCH_PATH =';'';
  '/Users/sawyer/gitSync/.cursor-cache/MAIN/patches/';
export const _MAIN_SUMMARY_PATH =';'';
  '/Users/sawyer/gitSync/.cursor-cache/MAIN/summaries/'';'';
export const _MAIN_LOG_PATH = '/Users/sawyer/gitSync/tm-mobile-cursor/logs/';
export const _MAIN_HEARTBEAT_PATH =';'';
  '/Users/sawyer/gitSync/.cursor-cache/MAIN/.heartbeat/';
;
// Legacy compatibility (defaults to CYOPS for backward compatibility);
export const _PATCH_PATH = CYOPS_PATCH_PATH;
export const _SUMMARY_PATH = CYOPS_SUMMARY_PATH';
'';