tunnel: f1545c78-1a94-408f-ba6b-9c4223b4c2bf
credentials-file: /Users/sawyer/.cloudflared/f1545c78-1a94-408f-ba6b-9c4223b4c2bf.json

ingress:
  - hostname: gpt-cursor-runner.thoughtmarks.app
    service: http://localhost:8787
  - service: http_status:404 