_metadata:
  major_version: 1
  minor_version: 0
display_information:
  name: gpt-cursor-webhook-thoughtmarks
  description: cursor's boss
  background_color: "#000000"
  long_description: "Robots using robots to control robots. This Slack app serves as a command interface for a GPT-powered hybrid automation pipeline, controlling Cursor through carefully structured instructional blocks and real-time patch orchestration."
settings:
  interactivity:
    is_enabled: true
    request_url: https://webhook-thoughtmarks.thoughtmarks.app/slack/events
  org_deploy_enabled: true
  socket_mode_enabled: true
  token_rotation_enabled: true
features:
  app_home:
    home_tab_enabled: true
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: Ghost
    always_online: true
  slash_commands:
    - command: /dashboard
      url: https://webhook-thoughtmarks.thoughtmarks.app/commands
      description: View Dashboard
      should_escape: false
    - command: /patch-pass
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Pass next pending patches
      should_escape: false
    - command: /patch-revert
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Revert the last applied patch
      should_escape: false
    - command: /restart-runner
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Restart the GPT-Cursor Runner service
      should_escape: false
    - command: /status-runner
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Check current runner status and health
      should_escape: false
    - command: /roadmap
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Show project roadmap and milestones
      should_escape: false
    - command: /kill
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Force stop the runner (emergency)
      should_escape: false
    - command: /status-push
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Status pulse now
      should_escape: false
    - command: /patch-preview
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Preview pending patches
      should_escape: false
    - command: /approve-screenshot
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Approve screenshot-based patches
      should_escape: false
    - command: /revert-phase
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Revert to previous phase
      should_escape: false
    - command: /log-phase-status
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Log current phase status
      should_escape: false
    - command: /cursor-mode
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Switch Cursor operation modes
      should_escape: false
    - command: /alert-runner-crash
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Send crash alert notification
      should_escape: false
    - command: /proceed
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Pass through proceed with options
      should_escape: false
    - command: /again
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Restart or retry last with optional manual input
      should_escape: false
    - command: /manual-revise
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Return to sender with notes for another attempt
      should_escape: false
    - command: /manual-append
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Conditional approval with notes
      should_escape: false
    - command: /interrupt
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Stop current operation and resume with new info
      should_escape: false
    - command: /troubleshoot
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Generate full hybrid diagnostic block
      should_escape: false
    - command: /send-with
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Request reissue of patch with more info
      should_escape: false
    - command: /troubleshoot-oversight
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Require human review after running fix
      should_escape: false
    - command: /watchdog-ping
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Ping watchdog
      should_escape: false
    - command: /toggle-runner
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Toggle between on (auto mode) and off
      should_escape: false
    - command: /runner-lock
      url: https://webhook-thoughtmarks.thoughtmarks.app/slack/commands
      description: Toggle lock runner (prevent changes)
      should_escape: false
oauth_config:
  redirect_urls:
    - https://webhook-thoughtmarks.thoughtmarks.app/slack/oauth/callback
  scopes:
    bot:
      - commands
      - chat:write
      - incoming-webhook
      - assistant:write
event_subscriptions:
  request_url: https://webhook-thoughtmarks.thoughtmarks.app/slack/events
  bot_events:
    - app_mention
    - message.channels
