tunnel: gpt-cursor-runner
credentials-file: ~/.cloudflared/f1545c78-1a94-408f-ba6b-9c4223b4c2bf.json

ingress:
  # Route everything to the monitor server on port 8787
  - hostname: gpt-cursor-runner.thoughtmarks.app
    service: http://localhost:8787
    originRequest:
      noTLSVerify: true
  # Catch-all rule (required by cloudflared)
  - service: http_status:404 