name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  validate-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Flake8, Mypy, and Python stubs
        run: |
          pip install flake8 mypy black types-requests types-psutil

      - name: Run Black (check style only)
        run: black --check dashboard/app.py

      - name: Run Flake8 (fail on error)
        run: flake8 dashboard/app.py

      - name: Run Mypy (fail on error)
        run: mypy --strict dashboard/app.py

      - name: Run validation script
        run: bash scripts/validate-dashboard.sh

  test:
    runs-on: ubuntu-latest
    needs: validate-dashboard
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r dashboard/requirements.txt
          pip install types-requests types-psutil

      - name: Run tests
        run: |
          python -m pytest tests/ -v

      - name: Test patch runner
        run: |
          # Create a test patch
          mkdir -p patches
          echo '{
            "id": "ci-test-patch",
            "role": "ui_patch",
            "description": "CI test patch",
            "target_file": "test_file.tsx",
            "patch": {
              "pattern": "test",
              "replacement": "✅ CI TEST PASSED"
            }
          }' > patches/ci-test-patch.json

          # Test dry run
          python -m gpt_cursor_runner.patch_runner --force

      - name: Test webhook handler
        run: |
          # Test webhook handler with sample data
          python -c "
          from gpt_cursor_runner.webhook_handler import process_hybrid_block
          import json

          test_block = {
              'id': 'ci-test',
              'role': 'ui_patch',
              'description': 'CI test',
              'target_file': 'test.tsx',
              'patch': {'pattern': 'test', 'replacement': 'replaced'}
          }

          result = process_hybrid_block(test_block)
          print(f'✅ Webhook handler test passed: {result}')
          "
