name: nightly-green-guard
on:
  schedule: [{ cron: "17 7 * * *" }]
  workflow_dispatch: {}
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 'lts/*' }
      - run: npm ci
      - name: ESLint fullscope
        run: |
          node scripts/ci/run_eslint_fast_now_once.js 120000 \
            "$HOME/.cache/eslint-report.now.json" \
            "$HOME/.cache/eslint-now.stdout.log" \
            "$HOME/.cache/eslint-now.stderr.log" \
            "scripts/g2o/**/*.{js,ts,tsx}" "scripts/ci/**/*.{js,ts,tsx}" \
            "scripts/metrics/**/*.{js,ts,tsx}" "scripts/validate/**/*.{js,ts,tsx}" "config/**/*.{js,ts,tsx}"
          node scripts/ci/validate_eslint_green.js
      - name: TSC
        run: npx tsc --noEmit
