name: release-gate
on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: "Branch to release from"
        required: true
        default: "develop"
permissions:
  contents: write
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.source_branch }}
          fetch-depth: 0
      - name: Node & PNPM setup
        uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Install deps (ci)
        run: npm ci
      - name: ESLint fullscope
        run: node scripts/ci/run_eslint_fast_now_once.js 120000 .cursor-cache/ROOT/.logs/eslint-report.now.json .cursor-cache/ROOT/.logs/eslint-now.stdout.log .cursor-cache/ROOT/.logs/eslint-now.stderr.log "scripts/{g2o,ci,metrics,validate}/**/*.{js,ts,tsx}" "config/**/*.{js,ts,tsx}"
      - name: TypeScript noEmit
        run: npx tsc --noEmit
      - name: Guards
        run: |
          node scripts/g2o/inline_node_e_guard.js --paths scripts/{g2o,ci,metrics,validate},config --mode fail-on-violation
          node scripts/ci/shebang_guard_precommit_once.js scripts/ci/*.js scripts/g2o/*.js
          node scripts/ci/ban_node_eval_guard.js --fail-on-find
      - name: Tag last green
        env:
          PAT: ${{ secrets.RELEASE_BOT_PAT }}
        run: |
          set -euo pipefail
          git config user.name  "release-bot"
          git config user.email "release-bot@users.noreply.github.com"
          SHA=$(git rev-parse HEAD)
          git tag -f "green/main" "$SHA"
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} "refs/tags/green/main" --force
      - name: Fast-forward main to source
        env:
          PAT: ${{ secrets.RELEASE_BOT_PAT }}
        run: |
          set -euo pipefail
          SRC="${{ github.event.inputs.source_branch }}"
          git fetch origin
          # Create a synthetic main at SRC head and force update (no protection)
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} "HEAD:refs/heads/main"
